### ISSUE TITLE
Synology DS 409+ upgrade_database AttributeError 'module' object has no attribute 'InitialSchema'

### ISSUE THREAD

**Issue by thmsndk** [clinton-hall/nzbToMedia#1614]
**Describe the bug**
Post Processing fails in what looks like an upgrade of the database and has been for a while, recently in an attempt to fix it I went in and did a manual update from git.

I found the following issue https://github.com/clinton-hall/nzbToMedia/issues/1516 but i'm uncertain how to run the commands.

Further more it now also warns me that python is not installed, I did install the Python3 synology package from SynoCommunity, but I now have both Python 2.7 and Python 3 packages installed.

The issue to me though, seems to be a failure in upgrading a database.

**Technical Specs**
1. Running on DS409+
2. Python version 2.7 / 3.3.2-005 
I currently have both packages installed, seems like it picks up the 2.7 one
3. Download Client NZBGet
4. Intended Media Management SickChill

**Expected behavior**
I expected the post process not to fail

**Log**
```
Mon Apr 29 2019 19:28:32	INFO	Executing post-process-script nzbToMedia/nzbToSickBeard.py for Game.Of.Thrones.S08E03.iNTERNAL.720p.HDTV.x264-TURBO.English
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: /volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/eol.py:139: LifetimeWarning: Python 2.7 is no longer supported.
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard:   warnings.warn(msg, LifetimeWarning)
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: [19:28:42] [INFO]::MAIN: Python v2.7 will reach end of life in 247 days.
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: [19:28:42] [WARNING]::MAIN: Please upgrade to a more recent Python version.
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: Changing to directory: /volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: -- Cleaning bytecode --
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard:          If errors occur, manual cleanup may be required.
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: -- Cleaning folders: ['libs', 'core'] --
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard:          If errors occur, manual cleanup may be required.
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: Returning to directory:  /volume1/@appstore/nzbget/var
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: -- Cleanup finished --
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: Traceback (most recent call last):
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard:   File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbToSickBeard.py", line 264, in <module>
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard:     result = nzbToMedia.main(sys.argv, section)
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard:   File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 789, in main
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard:     core.initialize(section)
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard:   File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/core/__init__.py", line 986, in initialize
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard:     main_db.upgrade_database(main_db.DBConnection(), databases.InitialSchema)
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: AttributeError: 'module' object has no attribute 'InitialSchema'
Mon Apr 29 2019 19:28:42	INFO	nzbToSickBeard: Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x30f23550>> ignored
Mon Apr 29 2019 19:28:42	ERROR	Post-process-script nzbToMedia/nzbToSickBeard.py for Game.Of.Thrones.S08E03.iNTERNAL.720p.HDTV.x264-TURBO.English failed (terminated with unknown status)
Mon Apr 29 2019 19:28:42	INFO	Collection Game.Of.Thrones.S08E03.iNTERNAL.720p.HDTV.x264-TURBO.English added to history
```

**Comment by labrys** [comment]
@thmsndk Open a command line terminal (e.g. using putty or ssh) and change to your nzbToMedia directory then run:
```
python -c "import cleanup; cleanup.force_clean_folder('libs', cleanup.FOLDER_STRUCTURE['libs'])"
```

**Comment by thmsndk** [comment]
@labrys I ran the following

> /volume1/@appstore/python/bin/python -c "import cleanup; cleanup.
force_clean_folder('libs', cleanup.FOLDER_STRUCTURE['libs'])"
Skipping required subfolders ['common', 'custom', 'py2', 'win']
Removing libs/babelfish
Removing libs/beets
Removing libs/bs4
Removing libs/chardet
Removing libs/concurrent
Removing libs/configobj
Removing libs/dateutil
Removing libs/dogpile
Removing libs/enum
Removing libs/enzyme
Removing libs/guessit
Removing libs/mutagen
Removing libs/pysrt
Removing libs/rebulk
Removing libs/requests
Removing libs/stevedore
Removing libs/subliminal
Removing libs/unidecode
Removing libs/yaml

rerean the post process, but i'm still getting this

> 

INFO | Wed May 01 2019 22:55:49 | nzbToSickBeard: Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x30f23550>> ignored
-- | -- | --
INFO | Wed May 01 2019 22:55:49 | nzbToSickBeard: AttributeError: 'module' object has no attribute 'InitialSchema'
INFO | Wed May 01 2019 22:55:49 | nzbToSickBeard: main_db.upgrade_database(main_db.DBConnection(), databases.InitialSchema)
INFO | Wed May 01 2019 22:55:49 | nzbToSickBeard: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/core/__init__.py", line 986, in initialize
INFO | Wed May 01 2019 22:55:49 | nzbToSickBeard: core.initialize(section)
INFO | Wed May 01 2019 22:55:49 | nzbToSickBeard: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 789, in main
INFO | Wed May 01 2019 22:55:49 | nzbToSickBeard: result = nzbToMedia.main(sys.argv, section)
INFO | Wed May 01 2019 22:55:49 | nzbToSickBeard: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbToSickBeard.py", line 264, in <module>
INFO | Wed May 01 2019 22:55:49 | nzbToSickBeard: Traceback (most recent call last):

**Comment by labrys** [comment]
Ok now please run the second half of the cleanup:

```
python -c "import cleanup; cleanup.force_clean_folder('core', cleanup.FOLDER_STRUCTURE['core'])"
```

**Comment by thmsndk** [comment]
@labrys 

>  /volume1/@appstore/python/bin/python -c "import cleanup; cleanup.
force_clean_folder('core', cleanup.FOLDER_STRUCTURE['core'])"
Skipping required subfolders ['auto_process', 'extractor', 'plugins', 'utils']
Removing core/autoProcess
Removing core/databases
Removing core/linktastic
Removing core/qbittorrent
Removing core/synchronousdeluge
Removing core/transcoder
Removing core/transmissionrpc
Removing core/utorrent

Ran it again and now sickchill reported success

Thanks a lot!

In regards to the Python 2.7 warning. will it just stop after ~244 days, or will the script be updated / changed to detect the python3 installation?

**Comment by clinton-hall** [comment]
in ~244 days the script will stop running (using python 2.7)
Currently the script will run the default Python (from the system path).

For your setup, even thought you have both Python 2.7 and Python 3.3 installed, it appears Python points to Python 2.7.
Hopefully this will be corrected with various Syno updates as we get closer to end of offical python 2.7 support...

if not, you can always set NZBGet to default to use python3
In NZBGet, settings, extension scripts set `ShellOverride` as
`py3=/usr/bin/python3` (substitute with the appropriate path).

This will force any .py extension script (called from NZBGet) to use Python3

**Comment by labrys** [comment]
@thmsndk Keep in mind Python 3.3 reached end-of-life almost 2 years ago and will also be unsupported.

It looks like there's a [Python 3.5.1](https://www.synology.com/en-us/dsm/packages/py3k) package available for the DS409+ which is still doesn't reach end of life for another 499 days.
