### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by Trotter73** [clinton-hall/nzbToMedia#1647]
**Describe the bug**
Since the update on 6/08/2019 post processing has been failing, the following error is shown in the Sab output...

TypeError: '>' not supported between instances of 'str' and 'int'

When I get a chance I will turn on debugging and run again... 

**Technical Specs**
1. Running on Windows 10 64Bit, 1903
2. Python version v3.7.3:ef4ec6ed12
3. Download Client SABnbzd 2.3.9
4. Intended Media Management Medusa,  0.3.4, Commit: 74c3f124fb599ad923e23f46fc320778b8b4217c

**Expected behavior**
Successful post processing

**Log**
[07:19:27] [INFO]::MAIN: Loading config from [C:\Utils\nzbToMedia\autoProcessMedia.cfg]
[07:19:27] [INFO]::MAIN: Python v3.7 will reach end of life in 1419 days.
[07:19:27] [INFO]::MAIN: Checking database structure...
[07:19:27] [INFO]::MAIN: Checking if source needs an update
[07:19:28] [INFO]::MAIN: No update needed
[07:19:28] [INFO]::MAIN: nzbToMedia Version:e165bbcefc9686c333978f79e72c0e3e8cba9c56 Branch:master (Windows 10)
[07:19:28] [WARNING]::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
[07:19:28] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[07:19:28] [INFO]::MAIN: #########################################################
[07:19:28] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[07:19:28] [INFO]::MAIN: #########################################################
[07:19:28] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[07:19:32] [INFO]::MAIN: Auto-detected SECTION:SickBeard
Changing to directory: C:\Utils\nzbToMedia

-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [WinError 2] The system cannot find the file specified

Directory is not a git repository

Force cleaning folder: libs
Skipping required subfolders ['common', 'custom', 'py2', 'win']
Removing libs\__pycache__

Force cleaning folder: core
Skipping required subfolders ['auto_process', 'extractor', 'plugins', 'utils']
Removing core\__pycache__
Returning to directory:  C:\Program Files\SABnzbd

-- Cleanup finished --

Traceback (most recent call last):
File "C:\Utils\nzbToMedia\nzbToSickBeard.py", line 273, in <module>
result = nzbToMedia.main(sys.argv, section)
File "C:\Utils\nzbToMedia\nzbToMedia.py", line 942, in main
download_id='', failure_link=''.join(args[8:]))
File "C:\Utils\nzbToMedia\nzbToMedia.py", line 796, in process
if extract == 1 and not (status > 0 and core.NOEXTRACTFAILED):
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by clinton-hall** [comment]
see #1646 
I have fixed this issue (hopefully) in `SAB-1` branch
https://github.com/clinton-hall/nzbToMedia/commit/5a534a6cdc8df6b4ccd0fc4b1821ce721139057b

please test latest `SAB-1` branch and test.
FWIW... this has been a bug for some time, but in Python 2 it just always evaluated as true, but in python 3 it gives an error.

**Comment by Trotter73** [comment]
Apologies! I'll give it a run around the block tonight and see how we go...

**Comment by clinton-hall** [comment]
no need for apologies. Just turns out 2 of you using SAB switched to python 3 and reported at almost the same time :)

**Comment by clinton-hall** [comment]
I have merged into nightly branch as this was confirmed working. SAB-1 branch is now gone, but you can move to nightly and keep up to date.

**Comment by Trotter73** [comment]
Hi,

Well I searched a couple of days before I posted, should have checked again. :)

Is there something I need to change to get onto the nightly branch, keeping mind I'm not running GIT. I downloaded the nightly zip but still get the error, I have a feeling it updated but that put me back to stable...

Maybe I should grab GIT at some point...

**Comment by clinton-hall** [comment]
git is easier... I would have thought the updater should still work with nightly...
I can merge up to master shortly and then see if your system updates to latest master...

if that still fails, send me full logs so i can see what it is saying.

**Comment by Trotter73** [comment]
I use it on my debian systems so it's not alien :) I think this would be the only project I would use it on though to be fair, if I have a rush of blood I'll give it a go :)

Fairly certain the updater put me back on master, she updated last night and is back processing again now, thanks again for all your efforts matey, really appreciated !

**Comment by PonyXpress** [comment]
Something has changed recently, as of 3 or 4 days ago I'm now getting nzbtomedia script errors

AttributeError: 'NoneType' object has no attribute 'isfile'

sabnzbd with sickchill, no changes made for many months. 

Are the errors Im seeing related to this thread topic, or something different?

So sab dl with no issues, script runs, but fails.  The end result is the file is in the dl directory, but it was not post processed by the script.  I can manually run a post process in SC and it works fine.
[sc test.txt](https://github.com/clinton-hall/nzbToMedia/files/3497394/sc.test.txt)

**Comment by Trotter73** [comment]
Looking at your log you are not on the latest version, you are 4 commits behind, 46b2e8998ce7c0e4b853272f0bdb06a558852c81 fixed it for me, I was getting a similar error...

**Comment by clinton-hall** [comment]
@PonyXpress 
The error you are seeing should only happen with an older version of nzbToMedia (i.e. V12.1.00 or earlier) when running Python3 and called from SABnzbd

So, if this was running fine, then I am suspecting your Python must have recently updated?

In anycase, once this updated to current nzbToMedia, this problem should indeed be fixed.

**Comment by PonyXpress** [comment]
We setup the script to auto update, so what would prevent it from updating as expected?

To update, is it still a manual download / install, and create a new cfg file?  Or is there an easier way?

Thank you!

**Comment by clinton-hall** [comment]
Your script shows that it was up-to-date with master when it ran.
I actually merged this fix into master last night (about 18 hours ago) so if the script last ran before that, I would expect it will auto-update on next run, and work as required.

If you are still seeing this issue, then a manual update may be required...
Manual download, and replace the existing version. But no need to create a new .cfg. Instead just make a backup/copy of your .cfg first and put it inside the new nzbToMedia folder.

**Comment by PonyXpress** [comment]
ok, thank you sir!  I will check it tomorrow and see if it updated.  I'd like to confirm the auto update is working before doing the manual.  Thanks again for your support and quick response!

I will let you know what happens.

Cheers!

**Comment by PonyXpress** [comment]
it updated and everything is working again  :)

Thanks!
