### ISSUE TITLE
NzbToMedia failed (terminated with unknown error)

### ISSUE THREAD

**Issue by kristianrp** [clinton-hall/nzbToMedia#1718]
**Describe the bug**
Post-processing fails with unknown error. I’m sing NZBget with Medusa. The problem started at the end of December 2019. 
I have tried to do git pull in nzbtomedia folder as well as cleaned up the .pyc files but with no change in the result.
I have also tried to update to Python 3 but it still uses version 2.x

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) 'Synology NAS'
2. Python version '2.x'
3. Download Client (NZBget, SABnbzd, Transmission) 'NZBGet'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) 'Medusa'

**Expected behavior**
Expected nzbtosickbeard to post-process my downloads.

**Log**
Mon Feb 10 2020 15:09:04	INFO	Move for Greys.Anatomy.S16E10.Help.Me.Through.the.Night.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb successful
Mon Feb 10 2020 15:09:04	INFO	Executing post-process-script nzbToMedia/nzbToSickBeard.py for Greys.Anatomy.S16E10.Help.Me.Through.the.Night.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb
Mon Feb 10 2020 15:09:05	INFO	nzbToSickBeard: Please use a newer version of Python.
Mon Feb 10 2020 15:09:05	INFO	nzbToSickBeard: Python End-of-Life for current versions:
Mon Feb 10 2020 15:09:05	INFO	nzbToSickBeard: v3.5 in  216 days
Mon Feb 10 2020 15:09:05	INFO	nzbToSickBeard: v3.6 in  682 days
Mon Feb 10 2020 15:09:05	INFO	nzbToSickBeard: v3.7 in 1233 days
Mon Feb 10 2020 15:09:05	INFO	nzbToSickBeard: v3.8 in 1708 days
Mon Feb 10 2020 15:09:05	INFO	nzbToSickBeard: Python 2.7 is no longer supported.
Mon Feb 10 2020 15:09:05	ERROR	Post-process-script nzbToMedia/nzbToSickBeard.py for Greys.Anatomy.S16E10.Help.Me.Through.the.Night.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb failed (terminated with unknown status)
Mon Feb 10 2020 15:09:05	INFO	Collection Greys.Anatomy.S16E10.Help.Me.Through.the.Night.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb added to history

**Comment by clinton-hall** [comment]
The problem started 1-Jan-2020 and has been fixed.
I know you say you did a git pull, but this appears not to have worked?

If you can update to a current version, this should run past that point.

Try
```
git reset --hard
git pull
```
if that doesn't work, you could try doing a fresh clone

**Comment by kristianrp** [comment]
I just tried the above in the nzbtomedia folder and it reports that it is already up to date.
A fresh clone as in reinstalling?

**Comment by clinton-hall** [comment]
Yes, For a fresh clone you can just move/rename and copy over the .cfg
```
cd nzbToMedia
cd ..
mv nzbToMedia nzbToMedia.old
git clone https://github.com/clinton-hall/nzbToMedia.git
cp nzbToMedia.old/autoProcessMedia.cfg nzbToMedia/autoProcessMedia.cfg
```
Then if everything is working as you want, you can just delete nzbToMedia.old

Otherwise you could check to see if any other traceback or errors are reported when running the script manually
```
cd nzbToMedia
./nzbToMedia.py
```

**Comment by kristianrp** [comment]
A fresh clone did not solve the issue.

The traceback seems to resolve in some issues:

admin@DiskStation:/volume1/@appstore/nzbToMedia$ ./nzbToMedia.py
/volume1/@appstore/nzbToMedia/eol.py:147: LifetimeWarning: Python 2.7 is no longer supported.
  warnings.warn(msg, LifetimeWarning)

-- Cleaning bytecode --

No bytecode to clean

-- Cleaning folders: [u'libs', u'core'] --
No folders to clean


-- Cleanup finished --

Traceback (most recent call last):
  File "./nzbToMedia.py", line 730, in <module>
    import core
  File "/volume1/@appstore/nzbToMedia/core/__init__.py", line 52, in <module>
    from core import logger, main_db, version_check, databases, transcoder
  File "/volume1/@appstore/nzbToMedia/core/databases.py", line 11, in <module>
    from core.utils import backup_versioned_file
  File "/volume1/@appstore/nzbToMedia/core/utils/__init__.py", line 14, in <module>
    from core.utils.download_info import get_download_info, update_download_info_status
  File "/volume1/@appstore/nzbToMedia/core/utils/download_info.py", line 14, in <module>
    database = main_db.DBConnection()
  File "/volume1/@appstore/nzbToMedia/core/main_db.py", line 65, in __init__
    self.connection = sqlite3.connect(db_filename(filename), 20)
sqlite3.OperationalError: unable to open database file

**Comment by clinton-hall** [comment]
ok, this is the database issue as reported at #1530

Are you able to review the suggestions there to see if they help at all. Looks like permissions preventing accessing the database file.

**Comment by kristianrp** [comment]
The owner of the nzbToMedia folder seems to be root and root has write access. 
How do I find out which user calls the script? And how do I then change the write permission or user so that it works together?

**Comment by clinton-hall** [comment]
The user that runs the script is not root, but is the user that runs NZBGet

Most likely 
user: svc-nzbget
Group: users

I am not sure how you xan verify that, perhaps look at the owner of downloaded files that have been downloaded by nzbget.

If the script and folder are changed to this ownership, that should work...

**Comment by kristianrp** [comment]
The user of nzbget is sc-nzbget and the group is nzbget.
I changed the owner of nzbToMedia to the same but the pp script still gives the same failure.

drwxr-xr-x  7 sc-nzbget                   nzbget                   4096 May 29  2018 nzbget
drwxrwxrwx  7 sc-nzbget                   nzbget                   4096 Feb 11 09:56 nzbToMedia

The permissions seems to be different. I have made a ‘chmod -R 777’ on the nzbToMedia folder. Was that wrong?

**Comment by clinton-hall** [comment]
Did you recursively change owner?

chown -R sc-nzbget:nzbget 

If this is the owner of all directories and sub directories, the script should be able to create the .db file when run by nzbget.

**Comment by kristianrp** [comment]
I don’t remember if I did that so just tried. It still fails.
But the traceback is different now

/volume1/@appstore/nzbToMedia/eol.py:147: LifetimeWarning: Python 2.7 is no longer supported.
  warnings.warn(msg, LifetimeWarning)

-- Cleaning bytecode --
Removing cleanup.pyc
Removing eol.pyc

Removing cleanup.pyc
Removing eol.pyc


-- Cleaning folders: [u'libs', u'core'] --
No folders to clean


-- Cleanup finished --

[21:42:42] [INFO]::MAIN: Loading config from [/volume1/@appstore/nzbToMedia/autoProcessMedia.cfg]
[21:42:42] [INFO]::MAIN: Python v2.7 reached end of life 41 days ago.
[21:42:42] [WARNING]::MAIN: Please upgrade to a more recent Python version.
[21:42:42] [INFO]::MAIN: Checking database structure...
[21:42:42] [INFO]::MAIN: Database upgrade required: Initial Schema
[21:42:43] [INFO]::MAIN: Checking if git needs an update
[21:42:44] [INFO]::MAIN: No update needed
[21:42:44] [INFO]::MAIN: nzbToMedia Version:5a6837759d90285664b3cb596662adb5bfbcb2a2 Branch:master (Linux 3.10.105)
[21:42:44] [WARNING]::MAIN: Failed to locate par2. Repair and rename using par files will not be possible!
[21:42:44] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
[21:42:44] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[21:42:44] [INFO]::MAIN: #########################################################
[21:42:44] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[21:42:44] [INFO]::MAIN: #########################################################
[21:42:44] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[21:42:44] [INFO]::MAIN: Searching  for mediafiles to post-process ...
[21:42:44] [ERROR]::MAIN: Failed to add directories from  for post-processing: [Errno 2] No such file or directory: ''
[21:42:44] [INFO]::MAIN: The ./nzbToMedia.py script completed successfully.

**Comment by clinton-hall** [comment]
So that shows the script is running. Presumably you called that manually as it shows no input args... when called from NZBGet this should receive the args and process correctly.

**Comment by kristianrp** [comment]
I called it manually.
From nzbget it gives the same failure as it started with. 

Med venlig hilsen / Best regards
Kristian Petersen

E-mail: mail@kristianpetersen.dk
Tlf.: 2629 9991

Sendt fra min iPhone

> Den 12. feb. 2020 kl. 03.28 skrev Clinton Hall <notifications@github.com>:
> 

﻿
So that shows the script is running. Presumably you called that manually as it shows no input args... when called from NZBGet this should receive the args and process correctly.

**Comment by kristianrp** [comment]
I called it manually, but from nzbget it still doesn't work either.

**Comment by clinton-hall** [comment]
the nzbget log relates to old options in your nzbget config and is not related to postprocessing scripts.

I think when you run the script as root, this creates log files and .db files with root privileges again, so you will need to again `chown -R sc-nzbget:nzbget` and then have nzbget call the script (without running it manually as root).

**Comment by kristianrp** [comment]
Just did that. It did not change the the outcome..

**Comment by clinton-hall** [comment]
So what is logged in NZBget now when the script is run?

**Comment by kristianrp** [comment]
The same as before:

INFO Wed Feb 12 2020 11:11:36 Collection Modern.Family.S11E12.Dead.on.A.Rival.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb added to history
--
ERROR Wed Feb 12 2020 11:11:36 Post-process-script nzbToMedia/nzbToSickBeard.py for Modern.Family.S11E12.Dead.on.A.Rival.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb failed (terminated with unknown status)
INFO Wed Feb 12 2020 11:11:36 nzbToSickBeard: Python 2.7 is no longer supported.
INFO Wed Feb 12 2020 11:11:36 nzbToSickBeard: v3.8 in 1706 days
INFO Wed Feb 12 2020 11:11:36 nzbToSickBeard: v3.7 in 1231 days
INFO Wed Feb 12 2020 11:11:36 nzbToSickBeard: v3.6 in 680 days
INFO Wed Feb 12 2020 11:11:36 nzbToSickBeard: v3.5 in 214 days
INFO Wed Feb 12 2020 11:11:36 nzbToSickBeard: Python End-of-Life for current versions:
INFO Wed Feb 12 2020 11:11:36 nzbToSickBeard: Please use a newer version of Python.
INFO Wed Feb 12 2020 11:11:36 Executing post-process-script nzbToMedia/nzbToSickBeard.py for Modern.Family.S11E12.Dead.on.A.Rival.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb


Is there a way to turn on a debugger that shows in more details what goes wrong?

**Comment by clinton-hall** [comment]
yes, edit autoProcessMedia.cfg
```
[General]
    log_debug = 1
```

But I note the first lines of logging are the same as before doing the update...
`INFO Wed Feb 12 2020 11:11:36 nzbToSickBeard: Python 2.7 is no longer supported.`
versus
`[21:42:42] [INFO]::MAIN: Python v2.7 reached end of life 41 days ago.`

so NZBGet is calling an older version of nzbToMedia... presumably from a different location to the script you have been manually running at `/volume1/@appstore/nzbToMedia`

**Comment by kristianrp** [comment]
The location in nzbget is:
/volume1/@appstore/nzbget/share/nzbget/scripts

Should it be just /volume1/@appstore/nzbget ?

**Comment by clinton-hall** [comment]
no, you don't need to change the location in nzbget, but you do need to ensure that the manual update is done on the correct location:
```
cd /volume1/@appstore/nzbget/share/nzbget/scripts/nzbget
git reset --hard
git pull
chown -R sc-nzbget:nzbget cd /volume1/@appstore/nzbget/share/nzbget/scripts/nzbget
```

**Comment by kristianrp** [comment]
Success! Thanks for having the patience to support me!!

**Comment by clinton-hall** [comment]
No worries. Glad it is sorted and sorry I didn't pick up on it earlier (all initial references were the relative paths within NZBGet)... in hindsight it seems very obvious looking at the different logs that there were 2 different versions/instances of the script!
